### ISSUE TITLE
Alpha channel in representations

### ISSUE THREAD

**Issue by tam10** [gabrielelanaro/chemview#31]
Transparency in molecular representations could allow comparisons between large geometries such as proteins and nanotubes in chemical reactions, optimisations etc. 

<img width="600" alt="alphatest" src="https://cloud.githubusercontent.com/assets/14977297/14714183/e79f63c2-07db-11e6-9809-2e457f2df15b.png">

For entire representations, it's fairly easy to allow transparency by adding:
    transparent: true, opacity: alpha
to the THREE material's arguments. However, a bit more effort would be needed to control individual atoms, but I can't think of a situation where varying transparencies could be useful.

For now, if it seems useful, I can add an opacity option for balls_and_sticks and isosurfaces.

**Comment by gabrielelanaro** [comment]
I think that's a pretty good idea, yes we can stick with a per-representation alpha value as there's probably not much use for a per-atom alpha value
