### ISSUE TITLE
Can't install the widget to jupyter manually. 

### ISSUE THREAD

**Issue by jdagdelen** [gabrielelanaro/chemview#42]
When I try to install the chemview widget as per the installation instructions, I get the following error:

`KeyError: 'The Python module chemview is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'`

**Comment by hainm** [comment]
quick fix is to adapt this code

https://github.com/arose/nglview/blob/master/nglview/__init__.py#L12-L18

**Comment by gabrielelanaro** [comment]
Sorry for the super-late answer. I can't manage to reproduce this code.

@hainm Is it necessary for newest version of jupyter? I'm wondering why I'm not having this problem on my installation

**Comment by hainm** [comment]
I am not sure. I got the similar error about 1 year ago: https://github.com/jupyter/notebook/issues/1624
